In [1]:
from sklearn.datasets import load_boston
import pandas as pd

In [2]:
boston = load_boston()

In [3]:
df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
df['price'] = boston['target']

In [4]:
hdf = df.head(10)
hdf

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,18.9

In [5]:
hdf.style.highlight_max()

In [6]:
hdf.style.background_gradient()

In [7]:
hdf.style.bar()

In [8]:
def odd_green(val):
    if val % 2 != 0:
        return 'color: green'
    return ''

In [9]:
hdf.style.applymap(odd_green)

In [10]:
def orange10(val):
    if val > 10:
        return 'background-color: orange'
    return ''

In [11]:
hdf.style.applymap(odd_green).applymap(orange10)

In [12]:
hdf.style.applymap(odd_green, subset=['ZN', 'RAD'])

In [13]:
def top20(col):
    is_top20 = col > col.quantile(.8)
    return ['font-weight: bold' if v else '' for v in is_top20]

In [14]:
hdf.style.apply(top20)

In [15]:
import qgrid

In [16]:
qgrid.nbinstall()

In [17]:
qgrid.show_grid(hdf)